version: 0.2
env:
  variables:
    CODEARTIFACT_PACKAGE_REGISTRY: "//amazon-${CODEARTIFACT_DOMAIN_OWNER}.d.codeartifact.${REGION}.amazonaws.com/${CODEARIFACT_PACKAGE_FORMAT}/${CODEARTIFACT_REPO_NAME}/"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
  pre_build:
    commands:
      - cat ~/.gitconfig || cat ~/.git/config
      - aws codeartifact login --domain ${CODEARTIFACT_DOMAIN_NAME} --domain-owner ${CODEARTIFACT_DOMAIN_OWNER} --repository ${CODEARTIFACT_REPO_NAME} --region ${REGION} --tool ${CODEARIFACT_PACKAGE_FORMAT}
      - node common/scripts/install-run-rush.js update

  build:
    commands:
      - node common/scripts/install-run-rush.js git-secrets-scan
      # Checks each project's package.json files and ensures that all dependencies are of the same version throughout the repository.
      - node common/scripts/install-run-rush.js check
      - node common/scripts/install-run-rush.js build --to "@${CODEARTIFACT_NAMESPACE}/${CODEARIFACT_PACKAGE_NAME}" -v
      - node common/scripts/install-run-rush.js test --to "@${CODEARTIFACT_NAMESPACE}/${CODEARIFACT_PACKAGE_NAME}" -v


