name: license-check-and-add
on:
  workflow_call:
    secrets: 
      gpg-private-key:
        required: true
      passphrase:
        required: true
      merge-token:
        required: true
      bot-user:
        required: true
      bot-user-email:
        required: true
  jobs:
    check-apache-license:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v3
          with:
            token: ${{secrets.merge-token}}
        - name: Check apache license
          id: check-apache-license
          run: node common/scripts/install-run-rush.js check-apache-license
          
    add-apache-license:
      runs-on: ubuntu-20.04
      if: needs.check-apache-license.results == failure
      needs: [check-apache-license]
      steps:
        - name: add-apache-license
          runs: node common/scripts/install-run-rush.js add-apache-license
        - name: Import GPG key
          uses: crazy-max/ghaction-import-gpg@v4
          with:
            gpg_private_key: ${{ secrets.gpg-private-key }}
            passphrase: ${{ secrets.passphrase }}
            git_user_signingkey: true
            git_commit_gpgsign: true
        
        - name: Auto commit updated files with Apache license headers
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "docs: Auto add Apache license headers [skip ci]"
            commit-options: '--no-verify --gpg-sign'
            commit_user_name: ${{ secrets.bot-user }}
            commit_user_email: ${{ secrets.bot-user-email }}
            branch: test-apache-header
          
