name: license-check-and-add
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - test-apache-header

jobs:
  check-apache-license:
    runs-on: ubuntu-20.04
    outputs:
      verified-apache-license: "${{steps.check-apache-license.outcome}}"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.MERGE_TOKEN}}
          fetch-depth: 0
      - name: Base Action
        uses: ./.github/actions/baseAction
      - name: Check apache license
        id: check-apache-license
        run: node common/scripts/install-run-rush.js check-apache-license
        continue-on-error: true
  add-apache-license:
    runs-on: ubuntu-20.04
    if: ${{ needs.check-apache-license.outputs.verified-apache-license == 'failure'}}
    needs: [check-apache-license]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.MERGE_TOKEN}}
          fetch-depth: 0
      
      - name: Base Action
        uses: ./.github/actions/baseAction
    
      - name: Add apache license
        run: node common/scripts/install-run-rush.js add-apache-license


      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
        
        # There's no way for github actions to push to a protected branch. This is a workaround
        # See https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/30
        # Conditional on if branch is protected or not
      - name: Temporaily disable branch protection on PR branch
        if: ${{ github.ref_protected == true }}
        uses: octokit/request-action@v2.x
        with:
          route: DELETE /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
          owner: awslabs
          repo: solution-spark-on-aws
          branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}

      - name: Auto commit updated files with Apache license headers
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: Auto add Apache license headers"
          commit_options: '--no-verify --gpg-sign'
          commit_user_name: ${{ secrets.BOT_USER }}
          commit_user_email: ${{ secrets.BOT_USER_EMAIL }}
          branch: ${{ github.ref_name }}

      - name: Enable branch protection on PR branch
        uses: octokit/request-action@v2.x
        if: always() && ${{ github.ref_protected == true }}  # Make sure to enable branch protection even if other steps fail
        with:
          route: POST /repos/{owner}/{repo}/branches/{branch}/protection/enforce_admins
          owner: awslabs
          repo: solution-spark-on-aws
          branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.MERGE_TOKEN }}